platform :ios, '9.0'

target ‘Fastalk' do
use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'JSQMessagesViewController'
pod 'SwiftGifOrigin', '~> 1.6.1'

end
